name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project and dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest httpx ruff mypy coverage
      - name: Lint (ruff)
        run: |
          ruff check .
      - name: Type check (mypy)
        run: |
          # allow missing imports in third-party libraries for now
          mypy --ignore-missing-imports . || true
      - name: Run tests with coverage
        run: |
          coverage run -m pytest -q
          coverage xml -i
      - name: Upload coverage to Actions artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
